// Progress used to be saved under level ids (E01, M12…), which change when levels are renumbered.
// It's now saved under a stable key from the title. This maps the ids that were live before the switch
// to their keys, so saved results carry over. Generated once from the deployed levels; never needs updating.
export const legacyIds: Record<string, string> = {
  E01: 'your-first-commit',
  E02: 'branching-out',
  E03: 'where-am-i',
  E04: 'back-and-forth',
  E05: 'fast-forward',
  E06: 'mark-the-release',
  E07: 'share-your-work',
  E08: 'catch-up-with-the-team',
  M01: 'two-roads-meet',
  M02: 'catch-up-with-main',
  M03: 'just-that-fix',
  M04: 'oops-go-back',
  M05: 'undo-in-public',
  M06: 'cherry-on-top',
  M07: 'wrong-branch',
  M08: 'straighten-it-out',
  M09: 'stacked-branches',
  M10: 'hotfix-everywhere',
  M11: 'lost-and-found',
  M12: 'merge-the-stack',
  M13: 'fetch-first',
  M14: 'one-after-another',
  M15: 'divergent-main',
  M16: 'spring-cleaning',
  M17: 'saved-from-detached-head',
  M18: 'ship-it-straight',
  M19: 'find-the-release',
  M20: 'merge-the-release-back',
  M21: 'fix-on-the-wrong-branch',
  P01: 'revert-the-revert',
  P02: 'wrong-base',
  P03: 'keys-in-the-history',
  P04: 'backport',
  P05: 'split-the-pr',
  P06: 'one-revert',
  P07: 'mixed-up-commits',
  P08: 'hotfix-from-production',
  P09: 'too-soon',
  P10: 'fix-forward',
  P11: 'lease-not-force',
  P12: 'wrong-release',
  P13: 'doubled-up',
  P14: 'both-release-lines',
  P15: 'lost-in-the-reset',
  P16: 'the-branch-is-gone',
  P17: 'half-cherry-picked',
  P18: 'backwards-merge',
  P19: 'no-merge-commit',
  P20: 'the-revert-came-along',
  P21: 'hotfix-from-develop',
  P22: 'rebased-main',
}
